version: '3.6'
services:
  nginx:
    image: nginx:latest
    #내부에서 개방할 포트 : 외부에서 접근할 포트
    ports: 
      - "445:445"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    container_name: "nginx"
    command: ["nginx", "-g", "daemon off;":]
    depends_on:
      - cnsapi

  cnsapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cnsapi
    ports:
      - "3001:3001"
    volumes: 
      - /home/opc/src/CNS_api/:/home/cns-fileUpload/



    

