version: '3.6'
services:
  nginx:
    image: nginx:1.0
    #내부에서 개방할 포트 : 외부에서 접근할 포트
    ports: 
      -"443:443"
    
    volumes:
      -
    container_name: "nginxProgram"
    depends_on:
      - backEnd

  backEnd:
    build: 
      context: .
      dockerfile: ./config/Dockerfile
    image: 
    container_name: LGAPI
    ports:
      -"3001:3001"
    volumes:



    

